install:
 - sudo pip install proselint
 - sudo apt-get install npm
 - sudo npm install -g markdown-link-check

script: 
 - proselint README.md
 - ./check_dead_links

language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
script:
    - "python master.py"
