install:
 - sudo pip install proselint
 - sudo apt-get install npm
 - sudo npm install -g markdown-link-check
 - pip install wheel
 - pip install pandas
 - sudo apt-get install r-base

script: 
 - proselint README.md
 - ./check_dead_links

language: python
python:
    - "2.7"
script:
    - "python master.py"
